[build]
  command = "npm run build"
  publish = "docs/.vitepress/dist"

# 为静态资源设置缓存头
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# 处理VuePress的SPA路由
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Language = [], Role = []} 